### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by valioDOTch** [lpalli/WGS84_CH1903#1]
Could you please specify which license is applicable to this work? :-)
Is it proprietary or FLOSS licensed?
Here's a list of licenses along with their standardized identifiers https://spdx.org/licenses/

**Comment by lpalli** [comment]
This work is just **a refactoring of the original code from swisstopo** as you can see reading the commit messages (https://github.com/lpalli/WGS84_CH1903/commits/master/wgs84_ch1903.js).
The original version from swisstopo is an old version, the current (http://www.swisstopo.admin.ch/internet/swisstopo/en/home/products/software/products/skripts.html) has some of my improvements already applied, I don't have checked for others changes.
Swisstopo **don't indicate an applicable license** therefore I don't know what licence **I can/must use for my work!**

You need a FLOSS license?

**Comment by valioDOTch** [comment]
Thank you for the fast answer.

In the meantime I also found the Swisstopo scripts and was bothered by the missing license there.
I wrote Swisstopo about this, suggesting that they may want to apply a CC-0 or an MIT license, which would make it possible to include it into free software as well as into most proprietary software.

**Comment by lpalli** [comment]
You can send me the Swisstopo response too?

**Comment by valioDOTch** [comment]
Sure, asap when I get it :+1: :)

**Comment by valioDOTch** [comment]
Ok, Swisstopo answered at last ^^

They decided to go for the MIT license and republished all the scripts with the respective license attached on http://www.swisstopo.admin.ch/internet/swisstopo/en/home/products/software/products/skripts.html :)

**Comment by lpalli** [comment]
Thanks for the good news :+1: 

I'll add the license to my work as soon as I can, probably this weekend.

**Comment by lpalli** [comment]
The swisstopo MIT license is now integrated in the repository.
